name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Run Cake Build Script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: Build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifacts/

      - name: Publish
        run:  |
           dotnet nuget push ./artifacts/*.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true && \
           dotnet tool install gpr -g && \
           gpr push ./artifacts/*.nupkg --repository https://github.com/${{github.repository}} -k ${{github.token}}